In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

df = pd.read_csv("cleaned_reviews.csv")
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["cleaned_text"])

vocab = vectorizer.get_feature_names_out()

print("Vocabulary:", vocab)
print("Size:", len(vocab))

Vocabulary: ['absolutely' 'according' 'add' 'adjust' 'afraid' 'allo' 'allrounder'
 'almost' 'along' 'also' 'always' 'amazed' 'amazing' 'angel' 'anoth'
 'anything' 'appealing' 'apple' 'around' 'assess' 'asus' 'atmos'
 'attractive' 'average' 'awesome' 'awsome' 'backlight' 'backup' 'bad'
 'balanced' 'balue' 'bank' 'battery' 'bbd' 'beat' 'benchmark' 'best'
 'better' 'big' 'billion' 'bit' 'black' 'blindly' 'body' 'book' 'bookto'
 'boot' 'bought' 'brands' 'bright' 'brilliant' 'browsing' 'budget' 'build'
 'built' 'butt' 'buy' 'buying' 'calls' 'came' 'camera' 'cant' 'card'
 'carry' 'cemra' 'changed' 'charge' 'charger' 'charging' 'cheap' 'choice'
 'choose' 'class' 'clear' 'clearer' 'coders' 'coding' 'college' 'color'
 'combination' 'comes' 'commendable' 'compact' 'companies' 'company'
 'compared' 'comparing' 'compete' 'competition' 'compromising'
 'conferences' 'confused' 'connected' 'connectivity' 'connects' 'cons'
 'core' 'cost' 'could' 'creators' 'crisp' 'customer' 'daily' 'days' 'deal'
 'de

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()
X_bow = bow.fit_transform(df["cleaned_text"])
X_bow.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [8]:
ohe = CountVectorizer(binary=True)
X_ohe = ohe.fit_transform(df["cleaned_text"])
X_bow.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df["cleaned_text"])
X_tfidf.toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21173971, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# sparse matrix cal

In [11]:
print("BoW shape:", X_bow.shape)
print("TF-IDF shape:", X_tfidf.shape)
print("OHE shape:", X_ohe.shape)

BoW shape: (100, 511)
TF-IDF shape: (100, 511)
OHE shape: (100, 511)


In [12]:
import numpy as np

sparsity = 1.0 - (X_bow.count_nonzero() / (X_bow.shape[0] * X_bow.shape[1]))
print("Sparsity:", sparsity)

Sparsity: 0.9752641878669276


In [13]:
feature_names = tfidf.get_feature_names_out()

scores = X_tfidf.toarray().sum(axis=0)

top_words = sorted(zip(feature_names, scores), key=lambda x: x[1], reverse=True)

print(top_words[:10])

[('laptop', 7.913902248626274), ('good', 7.620373288161301), ('product', 5.859453337913528), ('money', 5.13625451397045), ('performance', 5.021427345458023), ('best', 4.870214428901944), ('display', 4.766696045006782), ('battery', 4.7275670580535065), ('value', 4.585344796104821), ('price', 3.96536398563593)]


# Logistic regression part

In [18]:
def label_sentiment(text):
    positive_words = ["good", "great", "excellent", "amazing", "best", "awesome","nice"]
    
    for word in positive_words:
        if word in text:
            return 1  # positive
    
    return 0  # negative


df["label"] = df["cleaned_text"].apply(label_sentiment)

In [20]:
df[:10]

,review_text,cleaned_text,label
0,"Battery too good, It Feels Premium, If you are...",battery good feels premium looking overall com...,1
1,Definitely one of the best laptop in it's segm...,definitely one best laptop segment got less la...,1
2,"That is nice laptop at this price, if you can ...",nice laptop price find laptop college work cho...,1
3,Good product with good design and performance....,good product good design performance comparing...,1
4,Product is slim good for coders and creators E...,product slim good coders creators especially c...,1
5,Amazing product. Great performance. Sleek desi...,amazing product great performance sleek design...,1
6,samsung is master of all technologies....❣❣ ne...,samsung master technologies never doubt samsung,0
7,value for money. keyboard could be better,value money keyboard could better,0
8,"After using of almost 3 months, there is no do...",using almost months doubt decision right choos...,0
9,"Excellent laptop from samsung, really a unexpe...",excellent laptop samsung really unexpected one...,1


In [21]:
from sklearn.model_selection import train_test_split

X = df["cleaned_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

tfidf convertion

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidftrain = TfidfVectorizer()
# tfidftrain = CountVectorizer() bow testing

X_train_tfidf = tfidftrain.fit_transform(X_train)
X_test_tfidf = tfidftrain.transform(X_test)
X_train_tfidf.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Model train 

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [38]:
y_pred = model.predict(X_test_tfidf)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
      dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.75
              precision    recall  f1-score   support

           0       0.50      0.20      0.29         5
           1       0.78      0.93      0.85        15

    accuracy                           0.75        20
   macro avg       0.64      0.57      0.57        20
weighted avg       0.71      0.75      0.71        20

